import { Inter } from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import {Toaster} from "react-hot-toast";
import {UserProvider} from "@/app/provider/user/user-context";

import {SelectedMealProvider} from "@/app/provider/order/selection";
import {MealProvider} from "@/app/provider/meals/meals";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextUIProvider>
          <MealProvider>

           <SelectedMealProvider>
              <UserProvider>
                  {children}
              </UserProvider>
           </SelectedMealProvider>

          </MealProvider>

          <Toaster />
      </NextUIProvider>
      </body>
    </html>
  );
}
